const K='shionTogether.v01';
let db=JSON.parse(localStorage.getItem(K)||'null')||{name:'',events:[],todos:[],attendance:[],bg:''};
let viewDate=new Date(), selected=iso(new Date()), mode='event';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s); const save=()=>localStorage.setItem(K,JSON.stringify(db));
function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function nowTime(){return new Date().toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})}
function hello(){ $('#hello').textContent=db.name?`おかえり、${db.name}。`:'おかえり。'; $('#userName').value=db.name||''; if(db.bg)document.body.style.backgroundImage=`url(${db.bg})`;}
const titles={home:'紫音といっしょ。',schedule:'スケジュール',attendance:'勤怠',attendanceHistory:'勤務履歴',settings:'設定',todos:'ToDo リスト'};
let previousPage='home',histDate=new Date();
function go(id){let active=document.querySelector('.page.active')?.id||'home';if(id!==active)previousPage=active;$$('.page').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$('#title').textContent=titles[id];$('#back').classList.toggle('hidden',id==='home');if(id==='schedule')renderCal();if(id==='attendance')renderAtt();if(id==='attendanceHistory')renderHistory();if(id==='todos')renderTodos()}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#back').onclick=()=>{let active=document.querySelector('.page.active')?.id;if(active==='attendanceHistory')go('attendance');else if(active==='todos')go('schedule');else go('home')};
// Japanese holidays: fixed/common rules + equinox approximation, suitable for UI; substitute API/library in store build if desired.
function holiday(y,m,d){const key=`${m+1}-${d}`;let names={'1-1':'元日','2-11':'建国記念の日','2-23':'天皇誕生日','4-29':'昭和の日','5-3':'憲法記念日','5-4':'みどりの日','5-5':'こどもの日','8-11':'山の日','11-3':'文化の日','11-23':'勤労感謝の日'};if(names[key])return names[key];let dow=new Date(y,m,d).getDay(),week=Math.floor((d-1)/7)+1;if(m===0&&dow===1&&week===2)return'成人の日';if(m===6&&dow===1&&week===3)return'海の日';if(m===8&&dow===1&&week===3)return'敬老の日';if(m===9&&dow===1&&week===2)return'スポーツの日';let ve=Math.floor(20.8431+0.242194*(y-1980)-Math.floor((y-1980)/4));let ae=Math.floor(23.2488+0.242194*(y-1980)-Math.floor((y-1980)/4));if(m===2&&d===ve)return'春分の日';if(m===8&&d===ae)return'秋分の日';return''}
function renderCal(){let y=viewDate.getFullYear(),m=viewDate.getMonth();$('#monthLabel').textContent=`${y}年 ${m+1}月`;let c=$('#calendar');c.innerHTML='';let first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();for(let i=0;i<first;i++)c.append(document.createElement('span'));for(let d=1;d<=days;d++){let date=iso(new Date(y,m,d)),h=holiday(y,m,d),b=document.createElement('button');b.innerHTML=`${d}${h?`<small title="${h}">祝</small>`:''}`;let dow=new Date(y,m,d).getDay();if(dow===0)b.classList.add('sun');if(dow===6)b.classList.add('sat');if(h)b.classList.add('holiday');if(date===selected)b.classList.add('selected');if(db.events.some(e=>e.date===date))b.classList.add('has');b.onclick=()=>{selected=date;renderCal();renderDay()};c.append(b)}renderDay()}
function renderDay(){let es=db.events.filter(e=>e.date===selected).sort((a,b)=>(a.time||'').localeCompare(b.time||''));$('#dayPlans').innerHTML=`<strong>${selected}</strong>`+(es.length?es.map(e=>`<div class="item" data-event="${e.id}">${e.time||'終日'}　${esc(e.text)}</div>`).join(''):'<div class="item"><small>予定なし</small></div>');$$('[data-event]').forEach(x=>x.onclick=()=>openEditor('event',db.events.find(e=>e.id===x.dataset.event)))}
$('#prevMonth').onclick=()=>{viewDate.setMonth(viewDate.getMonth()-1);renderCal()};$('#nextMonth').onclick=()=>{viewDate.setMonth(viewDate.getMonth()+1);renderCal()};$('#eventAdd').onclick=()=>openEditor('event',{date:selected});$('#todoOpen').onclick=()=>go('todos');
function openEditor(m,item={}){mode=m;$('#editorTitle').textContent=m==='event'?'予定':'ToDo';$('#editId').value=item.id||'';$('#editText').value=item.text||'';$('#editDate').value=item.date||selected;$('#editTime').value=item.time||'';$('#editDeadline').value=item.deadline||'';$('#dateLabel').classList.toggle('hidden',m!=='event');$('#timeLabel').classList.toggle('hidden',m!=='event');$('#deadlineLabel').classList.toggle('hidden',m!=='todo');$('#deleteItem').classList.toggle('hidden',!item.id);$('#editor').showModal()}
$('#editorForm').addEventListener('submit',e=>{if(e.submitter?.value!=='default')return;e.preventDefault();let id=$('#editId').value||crypto.randomUUID(),text=$('#editText').value.trim();if(!text)return;if(mode==='event'){let x={id,text,date:$('#editDate').value,time:$('#editTime').value};db.events=db.events.filter(e=>e.id!==id);db.events.push(x)}else{let old=db.todos.find(t=>t.id===id);let x={id,text,deadline:$('#editDeadline').value,done:old?.done||false};db.todos=db.todos.filter(t=>t.id!==id);db.todos.push(x)}save();$('#editor').close();mode==='event'?renderCal():renderTodos()});
$('#deleteItem').onclick=e=>{e.preventDefault();let id=$('#editId').value;if(mode==='event')db.events=db.events.filter(x=>x.id!==id);else db.todos=db.todos.filter(x=>x.id!==id);save();$('#editor').close();mode==='event'?renderCal():renderTodos()};
$('#todoAdd').onclick=()=>openEditor('todo');function renderTodos(){$('#todoList').innerHTML=db.todos.length?db.todos.map(t=>`<div class="item ${t.done?'done':''}"><input class="todo-check" type="checkbox" data-check="${t.id}" ${t.done?'checked':''}><span data-todo="${t.id}">${esc(t.text)}</span> <small>${t.deadline||''}</small></div>`).join(''):'<div class="item"><small>ToDoなし</small></div>';$$('[data-check]').forEach(c=>c.onchange=()=>{let t=db.todos.find(x=>x.id===c.dataset.check);t.done=c.checked;save();renderTodos()});$$('[data-todo]').forEach(x=>x.onclick=()=>openEditor('todo',db.todos.find(t=>t.id===x.dataset.todo)))}
function todayRec(){let d=iso(new Date());return db.attendance.find(x=>x.date===d)}
function punch(type){let d=iso(new Date()),r=todayRec();if(type==='in'){if(!r){r={id:crypto.randomUUID(),date:d,in:nowTime(),out:'',off:false,breakMins:0};db.attendance.push(r)}else{r.in=nowTime();r.out='';r.off=false;r.breakMins=r.breakMins||0}$('#speech').textContent='行ってらっしゃい。一緒に頑張ろうな。'}if(type==='out'){if(!r||r.off){alert('先に出勤を押してな。');return}r.out=nowTime();r.off=false;$('#speech').textContent='今日も一日お疲れ様。よく頑張ったな。'}if(type==='off'){if(!r){r={id:crypto.randomUUID(),date:d,in:'',out:'',off:true,breakMins:0};db.attendance.push(r)}else Object.assign(r,{in:'',out:'',off:true,breakMins:0});$('#speech').textContent='ゆっくり休めよ。'}save();renderAtt()}
$('#clockIn').onclick=()=>punch('in');$('#clockOut').onclick=()=>punch('out');$('#dayOff').onclick=()=>punch('off');
function mins(r){if(!r.in||!r.out)return 0;let [ih,im]=r.in.split(':').map(Number),[oh,om]=r.out.split(':').map(Number);let raw=(oh*60+om)-(ih*60+im);if(raw<0)raw+=1440;return Math.max(0,raw-(Number(r.breakMins)||0))}function fmt(n){return`${Math.floor(n/60)}時間${n%60}分`}
function statusText(){let r=todayRec();if(!r)return'今日はまだ記録されていません';if(r.off)return'本日はお休みです';if(r.in&&!r.out)return`${r.in}に出勤しました`;if(r.in&&r.out)return`本日の勤務は終了しました（${fmt(mins(r))}）`;return'今日はまだ記録されていません'}
function renderAtt(){let ym=iso(new Date()).slice(0,7),rows=db.attendance.filter(r=>r.date.startsWith(ym)).sort((a,b)=>b.date.localeCompare(a.date)),total=rows.reduce((s,r)=>s+mins(r),0);$('#todayStatus').textContent=statusText();$('#attSummary').innerHTML=`<strong>${ym.slice(0,4)}年${ym.slice(5)}月</strong><div>出勤 ${rows.filter(r=>!r.off).length}日 ／ お休み ${rows.filter(r=>r.off).length}日</div><div>勤務合計 ${fmt(total)}</div>`}
$('#historyOpen').onclick=()=>{histDate=new Date();go('attendanceHistory')};$('#histPrev').onclick=()=>{histDate.setMonth(histDate.getMonth()-1);renderHistory()};$('#histNext').onclick=()=>{histDate.setMonth(histDate.getMonth()+1);renderHistory()};$('#manualAdd').onclick=()=>openAttEditor({date:iso(new Date()),in:'',out:'',off:false,breakMins:0});
function renderHistory(){let y=histDate.getFullYear(),m=histDate.getMonth(),ym=`${y}-${String(m+1).padStart(2,'0')}`,rows=db.attendance.filter(r=>r.date.startsWith(ym)).sort((a,b)=>b.date.localeCompare(a.date)),total=rows.reduce((s,r)=>s+mins(r),0),works=rows.filter(r=>!r.off),offs=rows.filter(r=>r.off);$('#histMonthLabel').textContent=`${y}年${m+1}月`;$('#histSummary').innerHTML=`<strong>勤務合計　${fmt(total)}</strong><div>出勤 ${works.length}日 ／ お休み ${offs.length}日</div>`;$('#historyList').innerHTML=rows.length?rows.map(r=>`<div class="history-card"><div class="date">${jpDate(r.date)}</div>${r.off?'<div class="worktime">お休み</div>':`<div class="worktime">${r.in||'--:--'} ～ ${r.out||'--:--'}</div><div class="meta">勤務 ${r.out?fmt(mins(r)):'未退勤'}${Number(r.breakMins)?` ／ 休憩 ${r.breakMins}分`:''}</div>`}<button class="edit" data-attedit="${r.id}">編集</button></div>`).join(''):'<div class="card empty">この月の勤務履歴はありません</div>';$$('[data-attedit]').forEach(b=>b.onclick=()=>openAttEditor(db.attendance.find(r=>r.id===b.dataset.attedit)))}
function jpDate(s){let d=new Date(s+'T00:00:00'),w='日月火水木金土'[d.getDay()];return`${d.getMonth()+1}月${d.getDate()}日（${w}）`}
function openAttEditor(r={}){$('#attEditId').value=r.id||'';$('#attEditDate').value=r.date||iso(new Date());$('#attEditType').value=r.off?'off':'work';$('#attEditIn').value=r.in||'';$('#attEditOut').value=r.out||'';$('#attEditBreak').value=Number(r.breakMins)||0;$('#attDelete').classList.toggle('hidden',!r.id);toggleWorkFields();$('#attEditor').showModal()}
function toggleWorkFields(){$('#workFields').classList.toggle('hidden',$('#attEditType').value==='off')}$('#attEditType').onchange=toggleWorkFields;
$('#attEditorForm').addEventListener('submit',e=>{if(e.submitter?.value!=='default')return;e.preventDefault();let id=$('#attEditId').value||crypto.randomUUID(),off=$('#attEditType').value==='off',r={id,date:$('#attEditDate').value,in:off?'':$('#attEditIn').value,out:off?'':$('#attEditOut').value,off,breakMins:off?0:Math.max(0,Number($('#attEditBreak').value)||0)};db.attendance=db.attendance.filter(x=>x.id!==id&&x.date!==r.date);db.attendance.push(r);save();$('#attEditor').close();renderHistory()});
$('#attDelete').onclick=e=>{e.preventDefault();let id=$('#attEditId').value;db.attendance=db.attendance.filter(x=>x.id!==id);save();$('#attEditor').close();renderHistory()};
$('#userName').onchange=e=>{db.name=e.target.value.trim();save();hello()};$('#bgFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader;r.onload=()=>{db.bg=r.result;save();hello()};r.readAsDataURL(f)};$('#resetBg').onclick=()=>{db.bg='';save();document.body.style.backgroundImage=''};
$('#exportBtn').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download=`shion-to-issho-backup-${iso(new Date())}.json`;a.click();URL.revokeObjectURL(a.href)};$('#importFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader;r.onload=()=>{try{db=JSON.parse(r.result);save();hello();alert('復元したよ。')}catch{alert('バックアップを読めなかった。')}};r.readAsText(f)};
function esc(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}hello();renderCal();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
